model:
  type: BEVFusion

  heads:
    object: null
    map:
      type: BEVSegmentationHead
      in_channels: 256
      grid_transform:
        input_scope: [[-50, 50, 0.5], [-50, 50, 0.5]]
        output_scope: [[-50, 50, 0.5], [-50, 50, 0.5]]
      classes: ${map_classes}
      loss: focal
